/*
 * @author BSG <dev@bsgroup.eu>
 * @copyright Better Software Group S.A.
 * @version: 1.0
 */
const PREFIX = "NOTIFICATION";
const PUSH_NOTIFICATION = `${PREFIX}_PUSH_NOTIFICATION`;
const SET_HUB_ERROR = `${PREFIX}_SET_HUB_ERROR`;
const SET_HUB_CONNECTION_STATE = `${PREFIX}_SET_HUB_CONNECTION_STATE`;
export const CONFIRM_READ = "CONFIRM_READ";
export const CONFIRM_READ_SUCCESS = "CONFIRM_READ_SUCCESS";
export const CONFIRM_READ_FAILURE = "CONFIRM_READ_FAILURE";

export const ActionTypes = {
  PUSH_NOTIFICATION,
  SET_HUB_ERROR,
  SET_HUB_CONNECTION_STATE,
  CONFIRM_READ,
  CONFIRM_READ_SUCCESS,
  CONFIRM_READ_FAILURE,
};
